

services:
  app:
    build: ./server
    container_name: kat_server
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: kat_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
